### ISSUE TITLE
Colors in notifications are messed up

### ISSUE THREAD

**Issue by D3SOX** [catppuccin/spicetify#10]
E.g. when adding something to the liked songs
![image](https://user-images.githubusercontent.com/24937357/161400048-1745658d-cbd2-48a7-a6f0-2d33c99deefc.png)

**Comment by davidbgonz** [comment]
The rosewater color scheme has the correct color setup for the notification popup. I forgot to carry over the notification colors to the other schemes. Thanks for reminding me! This should be a quick fix.

**Comment by davidbgonz** [comment]
This should now be resolved in #11
