### ISSUE TITLE
Playlist titles disappear on hover

### ISSUE THREAD

**Issue by akulakovsky** [catppuccin/spicetify#18]
https://user-images.githubusercontent.com/22990262/177403488-bb2eb318-41e6-4210-a26d-8d66368cac0f.mp4

Title/video pretty explain it all

**Comment by davidbgonz** [comment]
I cannot recreate the issue on my end. What version of Spotify/Spicetify are you running?

**Comment by akulakovsky** [comment]
Spotify for macOS (Apple Silicon)
1.1.88.612.gcc529952

spicetify --version                                                  ✔ 
2.10.2

**Comment by davidbgonz** [comment]
I'm on 1.1.84.716.gc5f8b819 on Arch. Once I get the next update I'll test again. They probably made some changes to the CSS classes again.

**Comment by dec1belPP** [comment]
Still facing this issue, any fixes?

**Comment by nekowinston** [comment]
The theme has been updated to the 0.2.0 spec, adding the new flavours, but sadly this issue still persists on macOS.

I personally don't use Spotify, so we'll have to wait until someone bothers to fix it on macOS, or Spotify updates its Linux client.

**Comment by Rekit0** [comment]
I had the same issue in windows 11, I fixed it by adding the following CSS code to `spicetify\Themes\catppuccin-mocha\user.css`:
```
.main-rootlist-rootlistItemLink:link, .main-rootlist-rootlistItemLink:visited {
    z-index: 1;
}
```
And then i reapplied the theme `spicetify config current_theme catppuccin-mocha`, `spicetify update`.

**Comment by nekowinston** [comment]
Including this with #23, since @ghostx31 tried it on Linux, and I just did on macOS. Changes nothing on Linux, fixes the issue on macOS.

Thanks for the CSS snippet @Rekit0.
