### ISSUE TITLE
Theme "catppuccin-mocha" not found, what do i do?

### ISSUE THREAD

**Issue by Cornelime920** [catppuccin/spicetify#21]
![image](https://user-images.githubusercontent.com/72398860/185609235-d5cb7336-6906-4dae-be91-a4edfab61ac9.png)

it was working earlier but after trying out another theme and trying to go back to this one, it keeps saying that the them is not found

I've put it everywhere, to the Spicetify-cli, .config, and theme folder and still it says the theme is not found

it also weirdly says that i already have the theme on.

**Comment by ghostx31** [comment]
Hey sorry for the delay. Can you share what commands you've run to enable it again?
Also it would be great if you could share the contents of your `~/.config/spicetify/config-xpui.ini` file, so that I can check if the extensions JS and the themes are added correctly.

**Comment by ghostx31** [comment]
Sure no worries with that @davidbgonz! I'd love your feedback on this and if you could determine a way to load the JS extensions in an easier manner. I don't code in JS so the current implementation feels kinda wonky. Thanks! :smile_cat:

**Comment by Stelicx** [comment]
Hi, have the same issue and I don't have that `~/.config/spicetify/config-xpui.ini` file in the folder. Any help? I would love to use this theme. I also put the theme files folders to every folder I can imagine but still getting the same error.
