### ISSUE TITLE
Theme doenst load properly in spotify

### ISSUE THREAD

**Issue by NamesCode** [catppuccin/spicetify#22]
<img width="809" alt="image" src="https://user-images.githubusercontent.com/86119896/190194073-011c7f05-d743-43fb-8976-0472f94080d5.png">
reinstalled the theme and still no effect

**Comment by ghostx31** [comment]
Hey! Can you let me know the steps you performed to enable the theme? Also, can you confirm if you can open Spotify without the theme? 
The image you linked hints at the fact that the theme is loading properly but its your Spotify client that isn't working/opening.

**Comment by NamesCode** [comment]
I preformed the steps on the catppuccin spicetify repo, It works without theme 
<img width="815" alt="image" src="https://user-images.githubusercontent.com/86119896/190198584-730015bf-6a85-4f07-94da-fb5b2ed74d8d.png">

**Comment by ghostx31** [comment]
I cannot reproduce this on my end on spicetify version `2.13.1` on Linux. Maybe @nekowinston on macOS can try and let me know if they face the same issue or not.

**Comment by nekowinston** [comment]
Just tried it on my end on macOS, also couldn't reproduce the issue.
I'll walk through the installation with @NamesCode on Discord.
