### ISSUE TITLE
The hovered playlist title is the same colour as the hover background

### ISSUE THREAD

**Issue by fowlis** [catppuccin/spicetify#25]
Preview of issue:
![](https://cdn.upload.systems/uploads/aTKoX36O.gif)
My config if it matters:
![](https://user-images.githubusercontent.com/84232621/190391337-b038de52-b6cc-492f-9be7-f5525f41384e.png)
Thanks in advance 👍

**Comment by nekowinston** [comment]
Hi there :wave:

This was an issue before, that should be fixed with https://github.com/catppuccin/spicetify/pull/23 from 13 hours ago. Are you using the latest version of the repo?

**Comment by fowlis** [comment]
Ah, sorry for not checking first. I'll give it a try

**Comment by fowlis** [comment]
Perfect, works fine now. Cheers!
