### ISSUE TITLE
Userstyle version?

### ISSUE THREAD

**Issue by Freeplayg** [catppuccin/spicetify#26]
For those who use Spotify in their browser, they can apply themes using the Stylus browser extension (NOT Stylish) with the UserCSS format, and upload to https://userstyles.world/ 

https://github.com/openstyles/stylus/wiki/Writing-UserCSS#creating

**Comment by ohitstom** [comment]
Whilst interesting this is not within the scope of this repo nor the Issues system...
This also wouldnt work with our css since the web-app for Spotify uses unmapped classes and Spicetify does not 👍🏻
