### ISSUE TITLE
Discovery on the Spicetify Marketplace

### ISSUE THREAD

**Issue by rollingmoai** [catppuccin/spicetify#4]
I would love to see this in the [Spicetify Marketplace](https://github.com/spicetify/spicetify-marketplace), here are the things that you need to do:

> ## Getting your extension/theme on Marketplace
> In order to show up in the custom app, you'll need to make a public GitHub repo that meets these requirements:
> * Have the matching **GitHub topic tag** ("spicetify-extensions" or "**spicetify-themes**")
> * Have a valid **`manifest.json`** in the root folder (format outlined below)

> ### Theme manifests
> * `name`: Your theme name
> * `description`: Description for your theme
> * `preview`: A path to your preview image. Must be relative to your project root. 
> * `usercss`: A path to your user.css file. Must be relative to your project root. 
> * `schemes`: A path to your color.ini file. Must be relative to your project root. 
> * `readme`: The filename for your extension's README file. Must be relative to your project root. 
> * `branch`: Optional branch to specify. Will use default branch if none. 
> * `authors`: Optional array of authors with names and urls. Will use repo owner if none. 
> 
> e.g. 
> ```json
> {
>     "name": "Theme Name",
>     "description": "Theme description",
>     "preview": "filepathFromGitRepo/theme.png",
>     "readme": "README.md",
>     "usercss": "filepathFromGitRepo/user.css",
>     "schemes": "filepathFromGitRepo/color.ini",
>     "branch": "beta-release",
>     "authors": [
>         { "name": "theRealPadster", "url": "https://github.com/theRealPadster" },
>         { "name": "CharlieS1103", "url": "https://github.com/CharlieS1103" }
>     ]
> }
> ```

See an example here: https://github.com/williamckha/spicetify-fluent

**Comment by davidbgonz** [comment]
Sorry for the delay. I'll take a look into this. There are some fixes that need to be applied from a previous update. After those are fixed I can see about adding this to the spicetify marketplace.
