### ISSUE TITLE
The play icon does not display correctly

### ISSUE THREAD

**Issue by XieLong233** [catppuccin/spicetify#43]
As the question, I used to apply catppuccin after changing the icon by changing other themes to apply catppuccin worked, now it does not work... I use catppuccin-latte. Comes with pictures
![Uploading QQ图片20230519144118.png…]()

**Comment by XieLong233** [comment]
In fact, it works when switching between different themes until the next reboot... My English is not good, please forgive me. Thank you for bringing such a comfortable theme.

**Comment by ohitstom** [comment]
Could you attempt to reupload a screenshot alongside your spicetify config please

**Comment by ohitstom** [comment]
stale
