### ISSUE TITLE
Merge variants onto one unified theme

### ISSUE THREAD

**Issue by kyrie25** [catppuccin/spicetify#45]
Unless there are some key differences that I am not aware of, each variants seems to have the same base stylings and companion extension but with different color palettes defined in `user.css`.

As such, it can all be defined in the theme's `color.ini` file (which supports custom variables) without needing to have duplicate code in the repository, also makes it easier for users to switch between color schemes without having to reinstall.

Color variables used in the extensions can also be parsed from `color.ini` using [`getComputedStyle`](https://developer.mozilla.org/en-US/docs/Web/API/Window/getComputedStyle) at runtime.

**Comment by ghostx31** [comment]
Fixed in 7a342fbcf71583439dcad564c78f05baaa05a1eb
