### ISSUE TITLE
Spotify starts blank after applying any theme

### ISSUE THREAD

**Issue by jadtl** [catppuccin/spicetify#46]
My Spotify client starts blank after applying any of the themes. Restoring my Spicetify backup fixes it.
<img width="1512" alt="Screenshot 2023-07-27 at 8 38 03 AM" src="https://github.com/catppuccin/spicetify/assets/56200813/9340face-6ea8-4f11-9e23-982742fbdef6">
<img width="1512" alt="Screenshot 2023-07-27 at 8 38 37 AM" src="https://github.com/catppuccin/spicetify/assets/56200813/92ceb0c5-75a3-4b6e-8813-f190f0c6978a">
<img width="1512" alt="Screenshot 2023-07-27 at 8 38 53 AM" src="https://github.com/catppuccin/spicetify/assets/56200813/6ac366ce-dae7-4fcd-a502-3d613f706149">
<img width="1512" alt="Screenshot 2023-07-27 at 8 39 24 AM" src="https://github.com/catppuccin/spicetify/assets/56200813/b6fd353b-c670-4393-9b07-72a21547de50">

**Comment by ohitstom** [comment]
This is not a catppuccin issue, please consult the Spicetify team on their discord 👍🏻

**Comment by ohitstom** [comment]
> > This is not a catppuccin issue, please consult the Spicetify team on their discord 👍🏻
> 
> Thanks for the pointer! Sorry for the mistake.

no need to apologize hope you get it sorted
