### ISSUE TITLE
Dark theme elements showing up on frappe

### ISSUE THREAD

**Issue by paul-brenner** [catppuccin/spicetify#49]
With the latest update and latte, I'm seeing some bits where dark themes are sneaking through such as
<img width="1040" alt="image" src="https://github.com/catppuccin/spicetify/assets/13038942/3f37baef-752d-4856-8f4d-03f1b1b7a68a">
and 
<img width="332" alt="image" src="https://github.com/catppuccin/spicetify/assets/13038942/bfe57229-05d7-40db-8b52-d4d5e5ee24ca">
Not sure if this is user error on my part, because I just need to wait for either spicetify or this repo to get some time to make changes, or perhaps a bug that is worth raising. Perhaps premature, but I'm raising it here just in case.

**Comment by ohitstom** [comment]
Im gonna need more info, such as spicetify config, marketplace installed tab, when you last installed/updated, etc

**Comment by paul-brenner** [comment]
wow, yes, very much user error on my part. I installed maybe 6 months ago? For whatever reason I didn't use the marketplace theme and installed some other way so probably whenever I've been updating I wasn't actually updating catppuccin-spicetify. When I went to the marketplace themes tab, saw that nothing was installed, installed catpuccin and everything is lovely. 

Thanks and sorry for the false alarm

**Comment by ohitstom** [comment]
> wow, yes, very much user error on my part. I installed maybe 6 months ago? For whatever reason I didn't use the marketplace theme and installed some other way so probably whenever I've been updating I wasn't actually updating catppuccin-spicetify. When I went to the marketplace themes tab, saw that nothing was installed, installed catpuccin and everything is lovely.
> 
> Thanks and sorry for the false alarm

Glad you got it fixed! Simple mistake to make aha
