### ISSUE TITLE
Cannot open drop-down lists in settings in Hyprland

### ISSUE THREAD

**Issue by Anomalocaridid** [catppuccin/spicetify#55]
I cannot open any of the drop-down lists in Spotify's settings when using this theme with Spicetify and using Hyprland as my window manager.

This issue was not present in the pre-#48 version of the theme.

**Comment by ohitstom** [comment]
this has nothing to do with this theme

**Comment by Anomalocaridid** [comment]
My bad. Thanks anyways.

**Comment by ohitstom** [comment]
> My bad. Thanks anyways.

did you figure out the issue? couldn't recreate it personally lol

**Comment by Anomalocaridid** [comment]
> did you figure out the issue? couldn't recreate it personally lol

Not really, but I think it's most likely a NixOS thing, judging by this issue that describes having the same problem she using this theme: https://github.com/the-argus/spicetify-nix/issues/44
