### ISSUE TITLE
Incorrect accent coloring when adding songs to playlist already on that playlist

### ISSUE THREAD

**Issue by fenwulf** [catppuccin/spicetify#57]
![image](https://github.com/catppuccin/spicetify/assets/155314733/dbfa464f-f50d-402e-b7fe-6fa68bc1f2f7)

As you can see in the above image, when adding duplicate tracks the coloring is messed up on the popup. Expected result is the outside border that is currently "red" should be background color (?).

If you are too busy to fix this, I can probably figure it out if this is a UI element in the css somewhere and PR.

Now that I am looking at this what should be the expected behavior here?

**Comment by ohitstom** [comment]
I'm away for new years for a couple days but I'll fix it ASAP when I get back

**Comment by ohitstom** [comment]
> If you remember to, please post the commit as a reply here before you close the issue. I would like to see what line fixes this! Thanks :)

I tend to link the issue to the PR so you should get an email when i open it! At college for the next couple days but i'll try and find time soon

**Comment by fenwulf** [comment]
Thank you!
