### ISSUE TITLE
Incorrect accent color when adding duplicate song to playlist (reopening previous issue)

### ISSUE THREAD

**Issue by fenwulf** [catppuccin/spicetify#59]
Unfortunately the commit did not seem to fix. I have triple checked that I updated it by removing all traces of spotify and spicetify (purging backup as well), then reinstalling everything from scratch. I still get this issue:

![image](https://github.com/catppuccin/spicetify/assets/155314733/7ccaea27-2d68-48fa-aa4a-d30cba743303)

Thanks for taking another look at it, no rush I am in uni for cs as well so I get the struggle hahaha

**Comment by ohitstom** [comment]
> Unfortunately the commit did not seem to fix. I have triple checked that I updated it by removing all traces of spotify and spicetify (purging backup as well), then reinstalling everything from scratch. I still get this issue:
> 
> ![image](https://github.com/catppuccin/spicetify/assets/155314733/7ccaea27-2d68-48fa-aa4a-d30cba743303)
> 
> Thanks for taking another look at it, no rush I am in uni for cs as well so I get the struggle hahaha

it's fixed on my end are you sure you are installing correctly

**Comment by fenwulf** [comment]
I have copied the changes directly from your commit:

![image](https://github.com/catppuccin/spicetify/assets/155314733/6c613844-8b2a-4e93-98f7-470f14a76f35)

**Comment by ohitstom** [comment]
> I have copied the changes directly from your commit:
> 
> ![image](https://github.com/catppuccin/spicetify/assets/155314733/6c613844-8b2a-4e93-98f7-470f14a76f35)

that is sass not css it needs compiling hence why you need to wait for it to be merged and our actions ran

**Comment by fenwulf** [comment]
Ahh ok. Thank you so much!
