### ISSUE TITLE
Change accent colour to black on the latte colour scheme

### ISSUE THREAD

**Issue by whoisgrayson** [catppuccin/spicetify#60]
Is there a way to change the accent colour to Black on the Latte colour scheme?

**Comment by ohitstom** [comment]
> Is there a way to change the accent colour to Black on the Latte colour scheme?

there's no black defined in the official palette though

**Comment by sgoudham** [comment]
@ohitstom can you help me understand why the spicetify theme has a `white` accent in the first place even though the colour is not part of the official palette?

I was going to initially disagree with adding `black` but feels even weirder to disallow `black` when `white` is already there...

**Comment by ohitstom** [comment]
> @ohitstom can you help me understand why the spicetify theme has a `white` accent in the first place even though the colour is not part of the official palette?
> 
> I was going to initially disagree with adding `black` but feels even weirder to disallow `black` when `white` is already there...

no idea it was here before my rewrite I just kept it in...

**Comment by sgoudham** [comment]
I'd be tempted to remove `white` so that the accents provided are only from the official palette, but it feels sort of mean to do that now.

Maybe removing it and adding some extra docs listing the instructions for adding a custom accent and recompiling the theme?

**Comment by ohitstom** [comment]
> I'd be tempted to remove `white` so that the accents provided are only from the official palette, but it feels sort of mean to do that now.
> 
> Maybe removing it and adding some extra docs listing the instructions for adding a custom accent and recompiling the theme? 

both colors are from *somewhere* in the palette but aren't technically accent colors...

It would feel wrong removing them because maybe some people just want the base colors without any accent at all?

Maybe as an alternative I can add an option for no accent color but at that point I'd still need to use that black color internally regardless so it's kind of redundant if you get what I mean?

idk just throwing some ideas out there!

**Comment by sgoudham** [comment]
The closest colour that I can find to the existing `white` is Latte Crust but it's not the same 
![image](https://github.com/catppuccin/spicetify/assets/58985301/fbea4faf-1d2a-43e6-9f9f-dd472b9d7bb0)

It looks like you've taken Latte Text to be the `black` accent in the latest #62 PR. 

Are we shipping with a default accent color already? No accent color with the default text color sounds good.

**Comment by ohitstom** [comment]
> No accent color option being text sounds good, should that be the default? Are we shipping with a default accent color already?

will modify the PR to make the default option no accent when I get some time, that seems like the best approach

**Comment by ohitstom** [comment]
@sgoudham PR is updated to match the changes you requested!
