### ISSUE TITLE
Theme seems to be broken ?

### ISSUE THREAD

**Issue by Magniquick** [catppuccin/spicetify#66]
<img width="2240" alt="Screenshot 2024-05-16 at 6 26 48 PM" src="https://github.com/catppuccin/spicetify/assets/67406856/b2b72461-7e1c-42a5-bdb3-bef50b3cdfab">

Notice the lack of spacing between the album cover pictures.
If this is indeed how its supposed to look, maybe update the [readme image](https://github.com/catppuccin/spicetify/blob/main/assets/preview.webp) ?

**Comment by uncenter** [comment]
How does it look without the Catppuccin theme enabled?

**Comment by Magniquick** [comment]
with `inject_css 0 inject_theme_js 0 replace_colors 0 overwrite_assets 0`
<img width="2240" alt="Screenshot 2024-05-16 at 6 57 15 PM" src="https://github.com/catppuccin/spicetify/assets/67406856/b1172b5d-86e3-4ce5-b225-3861583406b7">
or with Sleek / RosePine
<img width="2240" alt="Screenshot 2024-05-16 at 6 58 48 PM" src="https://github.com/catppuccin/spicetify/assets/67406856/571799f7-046d-41b1-8b87-7aeda40b8221">
_Should_ be reproducable with this: [spicetify.sh](https://github.com/catppuccin/spicetify/files/15335923/spicetify.txt) (requires zsh and some other stuff though)

**Comment by Magniquick** [comment]
Can confirm that this occurs even without anything else enabled.

**Comment by ohitstom** [comment]
> Can confirm that this occurs even without anything else enabled.

please update your spicetify and Spotify 👍

**Comment by Magniquick** [comment]
<img width="468" alt="Screenshot 2024-05-16 at 8 26 46 PM" src="https://github.com/catppuccin/spicetify/assets/67406856/2050f4ec-ba55-4272-a78a-277e2274d4a1">

Isn't this the latest ? I just updated

**Comment by Magniquick** [comment]
reproducible with `spicetify config inject_css 1 inject_theme_js 0 replace_colors 0 overwrite_assets 0`

**Comment by Magniquick** [comment]
That fixes it, but causes another bug (?):
<img width="2350" alt="Screenshot 2024-05-16 at 10 15 20 PM" src="https://github.com/catppuccin/spicetify/assets/67406856/bf1a6360-815d-46ae-b8db-9344e58b614e">
I'm talking about the strip on the top.

**Comment by ohitstom** [comment]
> That fixes it, but causes another bug (?): <img alt="Screenshot 2024-05-16 at 10 15 20 PM" width="2000" src="https://private-user-images.githubusercontent.com/67406856/331303129-bf1a6360-815d-46ae-b8db-9344e58b614e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4Nzg5NzksIm5iZiI6MTcxNTg3ODY3OSwicGF0aCI6Ii82NzQwNjg1Ni8zMzEzMDMxMjktYmYxYTYzNjAtODE1ZC00NmFlLWI4ZGItOTM0NGU1OGI2MTRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE2VDE2NTc1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZkNDAyYjU4MWI2MzY3ZDIyNWY1MTUzMTI3NWE5NTBlYmI0ZmU1Nzg0N2FkZTYwYjZiN2JkYWJiYTg1YTI2OTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GLf-wfcIgnXNw8pA9v9pKlybI8YZIHqEexLD5or04bE"> I'm talking about the strip on the top.

thats not a bug its a spotify feature that we used to remove, im not adding feature related parts to this theme to stay inline with what userstyles usually do (only making colour changes)

**Comment by Magniquick** [comment]
Ah, ok.
Sleek and nearly all the other themes in spicetify-themes seem to do that, but I understand if you dont want to impliment this.
