### ISSUE TITLE
Accent Colour in Spotify's Settings Page no longer found

### ISSUE THREAD

**Issue by true-Grand** [catppuccin/spicetify#67]
Perhaps could implement a way to change the accent manually when the settings page fails?

**Comment by ohitstom** [comment]
its there, actually report the bug so i can fix the root cause, versions please

**Comment by true-Grand** [comment]
Spotify for macOS (Apple Silicon)
1.2.37.701.ge66eb7bc
Spicetify v2.36.11

I just installed the Catpuccinn theme, so its the latest.

**Comment by true-Grand** [comment]
Uhm the button is still not there? Why is it completed...?
