### ISSUE TITLE
An incomprehensible black square.

### ISSUE THREAD

**Issue by IwantHappiness** [catppuccin/spicetify#69]
![2024-10-01_21-29-26](https://github.com/user-attachments/assets/9e576856-b27c-4380-b43d-3772dc8fc75d)

It only appears in my playlist.

**Comment by SrIzan10** [comment]
that should be a spotify ad

**Comment by IwantHappiness** [comment]
can't it be removed in any way ?  It's always hanging there.

**Comment by SrIzan10** [comment]
maybe an ad blocker?
